### ISSUE TITLE
Suggest another way to install clj-holmes

### ISSUE THREAD

**Issue by slipset** [clj-holmes/clj-holmes#19]
For a security product which suggests using `sudo curl ...` as a installation method is not a good thing.
This trains people to accept `sudo curl ...` as a installation method without thinking, and just copy paste it into their shell.

I see that what is suggested here is benign, but I'd suggest something more along the lines of 
```sh
$ curl -L https://github.com/clj-holmes/clj-holmes/releases/latest/download/clj-holmes -o /tmp/clj-holmes
$ cp /tmp/clj-holmes /some/path/on/your/system/
```
Also, one might need to make it runnable, with `chmod u+x` ?

**Comment by mthbernardes** [comment]
Makes totally sense, we're working on a PR which enhances the documentation https://github.com/clj-holmes/clj-holmes/pull/20 and also aim to remove this installation method.

**Comment by mthbernardes** [comment]
Issue solved in PR https://github.com/clj-holmes/clj-holmes/pull/20
