### ISSUE TITLE
Provide support to macOS

### ISSUE THREAD

**Issue by claynon** [clj-holmes/clj-holmes#34]
The current installation method only supports linuxes
When I try to execute clj-holmes in a mac I get the following error:
```
$ clj-holmes
-bash: /usr/local/bin/clj-holmes: cannot execute binary file
```

I believe this is caused because the binary is formated as an ELF
```
$ objdump -a $(which clj-holmes)

/usr/local/bin/clj-holmes:     file format elf64-x86-64
/usr/local/bin/clj-holmes
```

**Comment by mthbernardes** [comment]
Macos support implemented added.
https://github.com/clj-holmes/clj-holmes/releases/tag/v1.3.3
